

spring.config.import=classpath:application-Keys.properties

spring.application.name=ticketlink


spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XE
spring.datasource.username=${oracle_id}
spring.datasource.password=${oracle_pw}

spring.jpa.hibernate.ddl-auto=none

spring.jpa.generate-ddl=false
spring.jpa.show-sql=true
spring.jpa.database=oracle
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
server.servlet.session.timeout=60m
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false
spring.jackson.serialization.fail-on-empty-beans=false
# OAuth2 ????? ??
spring.security.oauth2.client.registration.kakao.client-id=	${Oauth.client_id}
spring.security.oauth2.client.registration.kakao.client-secret= ${Oauth.client_secret}
spring.security.oauth2.client.registration.kakao.authorization-grant-type=${Oauth.auth_grantType}
spring.security.oauth2.client.registration.kakao.scope=${Oauth.Scope}
spring.security.oauth2.client.registration.kakao.redirect-uri=${Oauth.redirect_uri}

# OAuth2 ??? ??
spring.security.oauth2.client.provider.kakao.authorization-uri=${Oauth.authorization-uri}
spring.security.oauth2.client.provider.kakao.token-uri=${Oauth.token-uri}
spring.security.oauth2.client.provider.kakao.user-info-uri=${Oauth.user-info-uri}
logging.file.name=logs/application.log
spring.web.resources.static-locations=classpath:/static/


jwt.secret= ${jwt.secret}
jwt.access.expiration= ${jwt.access.expiration}  
jwt.refresh.expiration= ${jwt.refresh.expiration}


server.port=8080
server.ssl.key-store=${server.ssl.key-store}
server.ssl.key-store-password=${server.ssl.key-store-password}
server.ssl.key-store-type=${server.ssl.key-store-type}
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

